export const PAGES = [
{
 id:'welcome', group:'Getting Started', title:'Welcome to BNB HEROES', icon:'◆',
 html:`<div class="eyebrow">PRESERVATION EDITION · NOVEMBER 2021</div><h1>BNB HEROES</h1><p class="lead">A medieval NFT collectible game built on BNB Smart Chain, designed around recruiting Heroes, upgrading a Stronghold, fighting enemies and earning rewards denominated in BNB.</p><div class="callout archive"><b>2021 documented</b><p>Contemporary listings described BNB HEROES as an Oracle-based NFT collectible card game focused on game economy, expansion and sustainability. The original whitepaper lived at <code>bnbheroes.gitbook.io/bnbheroes</code>.</p></div><h2 id="what-is-restored">What is restored here?</h2><p>This is not a newly invented whitepaper. It is a preservation build assembled from four evidence layers:</p><div class="cards"><div><b>BNB Chain state</b><span>Live contract storage, proxy implementations, NFT supply and gameplay parameters.</span></div><div><b>2021 Solidity</b><span>Surviving source for BNBHero, BNBHCharacter, BNBHPool, PriceOracle and Randoms.</span></div><div><b>2021 gameplay records</b><span>Beginner guides, screenshots, bot automation and player reports.</span></div><div><b>Official social posts</b><span>Hero introductions, launch information and project announcements.</span></div></div><h2 id="core-loop">The core loop</h2><ol class="steps"><li><b>Acquire BNBH</b><span>BNBH was the utility token used for in-game spending.</span></li><li><b>Recruit a Hero</b><span>Mint a randomized Hero NFT and wait 12 hours for arrival, or expedite.</span></li><li><b>Fight</b><span>Choose an enemy or Boss. Attack affects success, Armor affects HP loss, Speed affects BNB reward.</span></li><li><b>Reinvest</b><span>Upgrade Hero levels and Stronghold buildings to improve output and capacity.</span></li><li><b>Claim BNB</b><span>Rewards enter a vault with the legacy time-lock/tax schedule.</span></li></ol><div class="callout rebuild"><b>Preservation note</b><p>The original project was abandoned. This restored build keeps all real-money actions disabled by default. Historical economics are documented, not endorsed.</p></div>`
},
{
 id:'quick-start', group:'Getting Started', title:'Quick Start', icon:'⚔',
 html:`<h1>Quick Start</h1><p class="lead">The original game was intentionally simple. A player could move from wallet connection to the first fight in a few actions.</p><h2 id="requirements">Original requirements</h2><p>Contemporary guides instructed players to obtain BNBH, connect a BSC-compatible wallet, recruit a Hero and either wait for the Hero's arrival or pay an expedite fee.</p><table><thead><tr><th>Action</th><th>Original design</th><th>Recovered live state</th></tr></thead><tbody><tr><td>Recruit</td><td>Oracle-priced in BNBH</td><td>Character price is produced by PriceOracle</td></tr><tr><td>Arrival</td><td>12 hours</td><td><code>heroArrivalTime = 43,200s</code></td></tr><tr><td>Expedite</td><td>~10% of recruit price</td><td><code>getExpeditePrice = recruit / 10</code></td></tr><tr><td>Active Hero capacity</td><td>Starts at 2, raised by Town Inn</td><td><code>characterLimit = 2</code> + Town type 1 level</td></tr><tr><td>Max HP</td><td>1,000</td><td><code>maxHP = 1000</code></td></tr></tbody></table><h2 id="first-session">First session</h2><ol><li>Open <b>My Heroes</b> and recruit.</li><li>Use <b>Expedite</b> or wait 12 hours.</li><li>Open <b>Battle</b> and choose an encounter.</li><li>When XP reaches the level cap, unlock the next Hero level using BNBH.</li><li>Upgrade <b>Bank, Town Inn, Barracks</b> and <b>Training Grounds</b>.</li><li>Move excess Heroes to <b>Hero Reserves</b> when active capacity is full.</li></ol><div class="callout archive"><b>2021 beginner-guide evidence</b><p>A November 16, 2021 walkthrough explicitly covered Recruit, Town Building upgrades, Marketplace, PvE, Boss fights, withdrawals and Hero Reserves in this order.</p></div>`
},
{
 id:'heroes', group:'Gameplay', title:'Heroes & Recruitment', icon:'♞',
 html:`<h1>Heroes & Recruitment</h1><p class="lead">Heroes are ERC-721 NFTs represented by a compact on-chain stat structure. The surviving Character contract still contains the complete numeric template table.</p><div class="callout onchain"><b>On-chain confirmed</b><p>The BNBHCharacter collection reports <strong>309,732</strong> minted NFTs and stores <strong>21 Hero templates</strong>. The normal 100-slot recruit table uses templates 0–17; templates 18–20 are absent from those normal rolls.</p></div><h2 id="hero-structure">Hero structure</h2><pre><code>Hero {
  name, heroType, xp,
  attack, armor, speed,
  hp, tokenId, arrivalTime,
  level, heroClass
}</code></pre><h2 id="rarities">Rarity</h2><p>The recovered first 100 recruit slots produce this distribution:</p><div class="rarity-grid"><div class="common"><b>Common</b><strong>51%</strong></div><div class="uncommon"><b>Uncommon</b><strong>28%</strong></div><div class="rare"><b>Rare</b><strong>15%</strong></div><div class="epic"><b>Epic</b><strong>6%</strong></div><div class="legendary"><b>Legendary</b><strong>Special</strong></div></div><p>Legendary templates exist in storage but do not appear in the recovered normal 100-roll table. They may have been distributed through special/prize flows; the core contract includes an admin-only prize-Hero function.</p><h2 id="known-heroes">Identified Hero names</h2><table><thead><tr><th>Name</th><th>Rarity</th><th>Class</th><th>A / D / S</th><th>Evidence</th></tr></thead><tbody><tr><td>Arnulf of Esplin</td><td>Rare</td><td>Soldier</td><td>600 / 700 / 400</td><td>Official BNB_HEROES social post + on-chain template match</td></tr><tr><td>Elrik the Imbuer</td><td>Epic</td><td>Rogue</td><td>900 / 500 / 500</td><td>Official BNB_HEROES social post + on-chain template match</td></tr></tbody></table><div class="callout rebuild"><b>Why are other names shown as “Lost Hero” in the game?</b><p>The old metadata hostname <code>metadata.bnbheroes.io</code> no longer resolves. Numeric IDs and stats are preserved on-chain, but inventing missing names would reduce archival accuracy.</p></div>`
},
{
 id:'stats', group:'Gameplay', title:'Hero Stats & Levels', icon:'☷',
 html:`<h1>Hero Stats & Levels</h1><h2 id="attack">Attack</h2><p>Attack increases the chance of winning a fight. The Character contract calculates:</p><pre><code>successChance = baseChance[enemy] + attack * 10 / 100
win if random(0..999) + successChance > 1000</code></pre><p>In the user-facing guides this was explained approximately as <strong>+1 percentage point of success per +100 Attack</strong>.</p><h2 id="speed">Speed</h2><p>Speed increases BNB rewards after a successful fight:</p><pre><code>reward = baseBNBReward + baseBNBReward * speed / 1000</code></pre><p>A Hero with 1,000 Speed therefore receives roughly double the base BNB component before Bank bonuses.</p><h2 id="armor">Armor</h2><p>Armor reduces HP loss on a successful fight:</p><pre><code>hpLoss = max(0, requiredHP - armor / 10)</code></pre><h2 id="xp">XP and level locks</h2><p>A Hero stops progressing at the level XP cap until the next level is unlocked. The core tracks BNB rewards earned during the current level and charges a BNBH-denominated unlock cost tied to those earnings.</p><div class="callout onchain"><b>Recovered implementation detail</b><p>The surviving core's state-changing unlock path uses 20% of current-level BNB reward value (with a 0.01 BNB floor) converted to BNBH. A separate read helper in the same snapshot uses 25%, showing the live code evolved and was not perfectly internally consistent.</p></div>`
},
{
 id:'stronghold', group:'Gameplay', title:'Stronghold Buildings', icon:'♜',
 html:`<h1>Stronghold Buildings</h1><p class="lead">The Stronghold is the main long-term progression layer. Four building types each have three upgrade levels in the recovered contract.</p><div class="building-grid"><article><div>◆</div><h3>Bank</h3><p>Raises BNB rewards from successful fights.</p><b>Lv1 +3% · Lv2 +6% · Lv3 +16%</b></article><article><div>⌂</div><h3>Town Inn</h3><p>Adds one active Hero slot per level. Contemporary guide material also describes an HP/recovery benefit.</p><b>Capacity: 2 → 3 → 4 → 5</b></article><article><div>⚑</div><h3>Barracks</h3><p>Adds bonus XP to successful fights.</p><b>+30 · +60 · +90 XP</b></article><article><div>⚔</div><h3>Training Grounds</h3><p>Adds flat Attack, Armor and Speed.</p><b>+30 · +60 · +140 A/D/S</b></article></div><h2 id="upgrade-time">Upgrade time</h2><p>Recovered build-time storage contains 24h and 48h values depending on building/level. A November 2021 video specifically showed a 24-hour countdown on early upgrades.</p><h2 id="oracle-prices">Oracle-priced upgrades</h2><p>Town upgrade prices are expressed internally in BNB target values and converted into BNBH by the PriceOracle. This was intended to keep fiat/BNB-equivalent game costs more stable as BNBH's token price changed.</p><div class="callout archive"><b>2021 guide names confirmed</b><p>Town Inn, Bank, Training Grounds and Barracks are explicitly named in a contemporary beginner walkthrough.</p></div>`
},
{
 id:'combat', group:'Gameplay', title:'PvE & Boss Fights', icon:'⚔',
 html:`<h1>PvE & Boss Fights</h1><p class="lead">A fight is a single on-chain outcome calculation. Success gives XP and BNB reward; HP is consumed according to the encounter and Hero Armor.</p><h2 id="encounters">Recovered encounter table</h2><table><thead><tr><th>Type</th><th>Base chance</th><th>Base XP</th><th>Required HP</th><th>Base BNB</th></tr></thead><tbody><tr><td>Enemy 0</td><td>70.0%</td><td>100</td><td>200</td><td>0.00235125</td></tr><tr><td>Enemy 1</td><td>67.0%</td><td>110</td><td>200</td><td>0.00282150</td></tr><tr><td>Enemy 2</td><td>63.0%</td><td>120</td><td>200</td><td>0.00329175</td></tr><tr><td>Enemy 3</td><td>59.0%</td><td>130</td><td>200</td><td>0.00376200</td></tr><tr><td>Enemy 4</td><td>55.0%</td><td>150</td><td>200</td><td>0.00423225</td></tr><tr><td>Mage</td><td>51.0%</td><td>200</td><td>200</td><td>0.00470250</td></tr><tr><td>Boss</td><td>28.0%</td><td>400</td><td>400</td><td>0.01724250</td></tr></tbody></table><p class="fine">Enemy labels 0–4 are intentionally generic because their original display names have not yet been independently recovered. “Mage” and “Boss” are corroborated by a surviving 2021 automation repository.</p><h2 id="formula">Full reward path</h2><pre><code>success = random + baseChance + attackBonus > threshold
xp += baseEnemyXP + BarracksBonus
reward = baseReward * (1 + speed / 1000)
reward *= (1 + BankBonus)
hpLoss = requiredHP - armor / 10   // on success</code></pre><h2 id="stamina">HP recovery</h2><p>Max HP is 1,000 and the live Character contract stores <code>secondsPerHp = 86</code>, or roughly 11.6 HP every 1,000 seconds.</p>`
},
{
 id:'rewards', group:'Economy', title:'BNB Rewards & Claims', icon:'◇',
 html:`<h1>BNB Rewards & Claims</h1><p class="lead">BNB rewards accumulate in the game core and are paid from the BNBHPool contract when claimed.</p><h2 id="lock">48-hour first lock</h2><p>When a player's pending BNB balance changes from zero to positive, the core sets an unlock timestamp <strong>48 hours</strong> into the future.</p><h2 id="tax">Withdrawal tax schedule</h2><p>Once unlocked, the starting fee is 20%. It falls by 2 percentage points per full day until it reaches zero.</p><div class="tax-row"><span>Unlock<br><b>20%</b></span><span>+1 day<br><b>18%</b></span><span>+2<br><b>16%</b></span><span>+5<br><b>10%</b></span><span>+10<br><b>0%</b></span></div><p>After a claim, the pending balance is reset to zero and the next reward cycle starts the process again.</p><div class="callout onchain"><b>On-chain confirmed</b><p>The recovered core source implements this exact time-based tax flow and calls <code>BNBHPool.claimBNB(account, amount)</code>.</p></div>`
},
{
 id:'market-reserves', group:'Gameplay', title:'Marketplace & Hero Reserves', icon:'⚖',
 html:`<h1>Marketplace & Hero Reserves</h1><h2 id="marketplace">Marketplace</h2><p>A 2021 beginner guide includes a dedicated Marketplace screen for buying and selling Heroes. The marketplace UI is restored in the playable build, but its original settlement contract has not been conclusively recovered, so the preservation build uses local demo listings only.</p><h2 id="reserves">Hero Reserves</h2><p>The core contract contains direct support for a Hero bag/reserve system:</p><pre><code>moveHeroToBag(heroId)
takeHeroFromBag(heroId)
getHeroesInBag(account)</code></pre><p>Moving a Hero into the bag transfers the NFT to the game contract and records the timestamp. Returning it restores the Hero and adjusts the stamina timestamp so reserve time is handled by the legacy logic.</p><div class="callout onchain"><b>Live setting</b><p>The core currently reports <strong>maxHeroCount = 20</strong> for the reserve bag, while an earlier source snapshot initialized it to 10. This is another example of live parameters changing after deployment.</p></div>`
},
{
 id:'tokenomics', group:'Economy', title:'BNBH Token & Tokenomics', icon:'◈',
 html:`<h1>BNBH Token & Tokenomics</h1><p class="lead">BNBH is the utility token used to recruit Heroes, expedite arrival, upgrade Stronghold buildings and unlock Hero levels.</p><h2 id="supply">Supply</h2><table><tbody><tr><th>Token</th><td>BNBHeroToken (BNBH)</td></tr><tr><th>Contract</th><td><code>0xD25631648E3Ad4863332319E8E0d6f2A8EC6f267</code></td></tr><tr><th>Max supply</th><td>100,000,000 BNBH</td></tr><tr><th>Decimals</th><td>18</td></tr></tbody></table><h2 id="early-token-plan">Early public token plan</h2><p>A pre-launch November 2021 presentation documented a 100M supply plan of approximately 36% burn, 4% private presale, 30% public presale, 21% liquidity pool and 9% development/marketing.</p><h2 id="spending">In-game spending</h2><p>Official late-November project material stated that <strong>70% of money spent in the game returned to the BNB Rewards Pool and 30% was burned</strong>. The recovered game-core source implements a configurable <code>dividePercent</code> and currently reads 70.</p><h2 id="transfer-fees">Token transfer fees</h2><div class="callout archive"><b>Version warning</b><p>Early marketing/whitepaper excerpts advertised 12% buy/sell slippage (11% BNB rewards + 1% liquidity). A surviving November 27 source snapshot initializes the token at 13% BNB fee + 2% liquidity, and both values are owner-settable. Historical live fees therefore changed over time; this restoration does not collapse them into one “forever” number.</p></div>`
},
{
 id:'oracle', group:'Economy', title:'Oracle & Sustainability', icon:'◎',
 html:`<h1>Oracle & Sustainability</h1><p>BNB HEROES used a PriceOracle to express important game costs in BNB-equivalent terms and convert those costs into BNBH. The design goal was to prevent a rapidly changing BNBH market price from making recruitment and upgrades unusably cheap or expensive.</p><h2 id="character-price">Character pricing</h2><pre><code>characterPriceInBNB = 0.30 BNB   // recovered source snapshot
BNBH cost = BNB target × BNBH-per-BNB oracle price
expedite = character price / 10</code></pre><p>Contemporary user guides mention ~0.2–0.3 BNB target recruitment values at different moments, consistent with parameters being updated during the live period.</p><h2 id="price-source">Price source</h2><p>The recovered Oracle asks PancakeSwap's router for the amount of BNBH obtainable from 1 BNB/WBNB and stores that result as <code>bnbhPrice</code>.</p><div class="callout rebuild"><b>Security note for the revival</b><p>The restoration keeps oracle/economic actions read-only. Any future real-money relaunch should use a modern audited oracle design and should not simply redeploy the 2021 contracts.</p></div>`
},
{
 id:'arena-expansions', group:'Roadmap', title:'Arena, Missions & Expansions', icon:'♛',
 html:`<h1>Arena, Missions & Expansions</h1><h2 id="arena">BNB Arena Run</h2><p>Contemporary official descriptions advertised <strong>BNB Arena Run</strong> as a weekly competition with a BNB prize pool. A November 4 presentation also described weekly battle events, special missions and Arena competition.</p><h2 id="idle">Idle missions</h2><p>Late-November official project material stated that players could assign characters to idle tasks in exchange for BNBH. This system is documented here but is not present in the recovered core contract snapshot and is therefore not enabled in the revival game yet.</p><h2 id="expansions">Planned expansions</h2><div class="cards"><div><b>BNB Champions</b><span>Planned expansion after the initial Hero mint milestone.</span></div><div><b>BNB Mercenaries</b><span>Second announced expansion in official late-November material.</span></div></div><p>Early promotional posts tied BNB Champions to the original 10,000-Hero milestone. The live Character collection later grew far beyond that early cap, reaching 309,732 NFTs.</p>`
},
{
 id:'contracts', group:'Technical', title:'Recovered Contracts', icon:'⌘',
 html:`<h1>Recovered Contracts</h1><p class="lead">These addresses were read from the real BNB HEROES core and independently corroborated by surviving 2021 client code.</p><table class="contracts"><thead><tr><th>Component</th><th>Address</th></tr></thead><tbody><tr><td>BNBH Token</td><td><code>0xD25631648E3Ad4863332319E8E0d6f2A8EC6f267</code></td></tr><tr><td>Game Core proxy</td><td><code>0xde9fFb228C1789FEf3F08014498F2b16c57db855</code></td></tr><tr><td>BNBHCharacter proxy</td><td><code>0x6DA72F24c56197Dcf6B8920baCb183F6ccca8b01</code></td></tr><tr><td>BNB Rewards Pool</td><td><code>0xdE8c58d082d39D04DC2e5241a3a65911454674CD</code></td></tr><tr><td>Price Oracle</td><td><code>0xD160bbDED5cFF79b126443EefCB28F3b67991140</code></td></tr><tr><td>Randoms</td><td><code>0xB81Cd7e88feAda830E7C1095909db3F5336d8664</code></td></tr></tbody></table><h2 id="proxy-implementations">Recovered EIP-1967 implementations</h2><table><tbody><tr><th>Core implementation</th><td><code>0x7e12cb515361e1fd2adac92018e70ac76019b07d</code></td></tr><tr><th>Character implementation</th><td><code>0x3d833ffb8a19dda5e44fc34d5ab666fa24c6e9e6</code></td></tr><tr><th>Oracle implementation</th><td><code>0x247e23bace48bba978466675e663afaad082cb69</code></td></tr></tbody></table><div class="callout archive"><b>False lead corrected</b><p><code>0x9051e0...</code>, still listed by some game directories as a BNB HEROES contract, is not the game core. Runtime selector analysis identifies it as a fee/liquidity BEP-20-style token contract.</p></div>`
},
{
 id:'source-recovery', group:'Technical', title:'Source Recovery', icon:'⌬',
 html:`<h1>Source Recovery</h1><h2 id="solidity">Solidity repository</h2><p>The 2021 repository <code>neko1101/hardhat-proxy-bnbh-example</code> contains source trees for:</p><ul><li>BNBHero</li><li>BNBHCharacter</li><li>BNBHPool</li><li>BNBHPriceOracle</li><li>ChainlinkRandoms</li><li>BNBHeroToken</li></ul><p>Its commit history is dated November 27, 2021. Function names, storage, constants and behavior closely match live BNB Chain state, while some live values reflect later parameter updates.</p><h2 id="clients">Surviving clients and bots</h2><p>A December 2021 Nim automation/client independently embeds the correct core, token and oracle addresses and implements the live ABI for <code>createNewHero</code>, <code>fight</code>, <code>upgradeTown</code>, <code>expediteHero</code>, level unlock and reward claim.</p><p>A separate AutoIt bot repository contains UI recognition fragments named <code>myHeroes</code>, <code>goToMage</code>, <code>fightMage</code>, <code>goToBoss</code>, <code>unlock</code> and MetaMask confirmation states. Those fragments helped identify the structure of the old interface.</p>`
},
{
 id:'preservation', group:'Technical', title:'Preservation Status', icon:'☑',
 html:`<h1>Preservation Status</h1><p class="lead">“Finished” here means a complete playable preservation build of the recoverable game loop and a reconstructed whitepaper, not a claim that every lost pixel or sentence of the original 2021 website has been recovered.</p><h2 id="complete">Implemented</h2><ul class="check"><li>Recruitment probability table from live chain state</li><li>12-hour Hero arrival and expedite</li><li>Hero capacity and Reserves</li><li>Attack / Armor / Speed combat formula</li><li>Seven recovered encounter parameter sets</li><li>HP recovery and XP progression</li><li>Level unlock economy</li><li>Four Stronghold buildings and three levels</li><li>BNB reward vault, 48h lock and declining claim tax</li><li>Marketplace preservation screen</li><li>Activity / battle log</li><li>Responsive medieval UI</li><li>Restored GitBook-style whitepaper</li><li>Live-chain forensic snapshot script</li><li>Automated deterministic engine tests</li></ul><h2 id="irrecoverable">Still historically missing</h2><ul><li>The original metadata server contents for most Hero names/art.</li><li>The exact source bundle of <code>play.bnbheroes.io</code>.</li><li>Some original enemy display names/art.</li><li>The exact original GitBook prose and page order.</li></ul><div class="callout rebuild"><b>Archival discipline</b><p>Where a name, asset or sentence cannot be substantiated, the revival labels it as reconstructed or unknown instead of fabricating a false “original.”</p></div>`
},
{
 id:'sources', group:'Appendix', title:'Sources & Provenance', icon:'▤',
 html:`<h1>Sources & Provenance</h1><p>Key public evidence used in this restoration:</p><ol class="sources"><li><b>BNB Chain mainnet</b> — direct JSON-RPC reads of core, Character, Pool, Oracle and proxy implementation slots.</li><li><b>neko1101/hardhat-proxy-bnbh-example</b> — November 27, 2021 Solidity source snapshot.</li><li><b>130347665/BNBHeroes</b> — December 2021 Nim client/automation with live addresses and ABI.</li><li><b>pathawee1993/bnb-heroes-bot</b> — 2021 AutoIt UI automation fragments.</li><li><b>theAPEcoach, “BNB HEROES BEGINNERS GUIDE”</b> — YouTube, November 16, 2021; Recruit, Town, Marketplace, PvE, Boss, Claims, Reserves.</li><li><b>theAPEcoach, BNB HEROES overview</b> — YouTube, November 4, 2021; early token plan, roadmap, Arena, Hero rarity/stat model.</li><li><b>BNB_HEROES official social archive</b> — Arnulf of Esplin and Elrik the Imbuer introductions.</li><li><b>Newsfile, November 29, 2021</b> — official project release describing BNB rewards, 70/30 in-game spend flow, Arena and planned expansions.</li><li><b>LBank listing notice, November 23, 2021</b> — project description and original GitBook URL.</li><li><b>Contemporary player guides/reports</b> — cross-checks for claim timing, building effects and gameplay loop.</li></ol><h2 id="confidence">Evidence labels</h2><p><span class="badge onchain">On-chain confirmed</span> means directly read from BNB Chain or deterministically derived from verified runtime behavior.</p><p><span class="badge archive">2021 documented</span> means supported by a dated contemporary video, source repository, official post or article.</p><p><span class="badge rebuild">Reconstructed</span> means recreated to complete the preservation experience while explicitly distinguished from recovered original material.</p>`
}
];
